import { CategoryEnum, IngredientEnum, QuantityEnum } from "@prisma/client";

export type RecipeProps = {
  id: number;
  title: string;
  description: string;
  servings: number;
  prepTime: number;
  cookTime: number;
  instructions: string;
  photo: string;
  authorId: string;
  ingredients: Array<{
    ingredientId: number;
    quantity: string;
    quantity_type: string;
  }>;
  categories: Array<{
    id: number;
    categoryId: number;
  }>;
  createdAt?: Date;
};

export const QUANTITY_TYPE = [
  "GRAMS",
  "KILOGRAMS",
  "MILLILITERS",
  "LITERS",
  "TABLESPOON",
  "TEASPOON",
  "CUP",
  "GLASS",
  "PINCH",
  "UNIT",
  "PIECE",
  "SLICE",
  "CAN",
];
export const QUANTITY_TYPE_LABELS: Record<string, string> = {
  [QuantityEnum.GRAMS]: "Gramas",
  [QuantityEnum.KILOGRAMS]: "Quilogramas",
  [QuantityEnum.MILLILITERS]: "Mililitros",
  [QuantityEnum.LITERS]: "Litros",
  [QuantityEnum.TABLESPOON]: "Colher de Sopa",
  [QuantityEnum.TEASPOON]: "Colher de Chá",
  [QuantityEnum.CUP]: "Xicara",
  [QuantityEnum.GLASS]: "Copo",
  [QuantityEnum.PINCH]: "Pitada",
  [QuantityEnum.UNIT]: "Unidade",
  [QuantityEnum.PIECE]: "Pedaço",
  [QuantityEnum.SLICE]: "Fatia",
};

// constantes das categorias
export const CATEGORIES = [
  "GRAINS",
  "DAIRY",
  "MEATS",
  "OILS_FATS",
  "VEGETABLES",
  "FRUITS",
  "PASTA",
  "BREADS",
  "LEGUMES",
  "DESSERT",
];
export const CATEGORIES_LABELS: Record<string, string> = {
  [CategoryEnum.GRAINS]: "Graos",
  [CategoryEnum.DAIRY]: "Laticinios",
  [CategoryEnum.MEATS]: "Carne",
  [CategoryEnum.OILS_FATS]: "Oleos e Gorduras",
  [CategoryEnum.VEGETABLES]: "Vegetais",
  [CategoryEnum.FRUITS]: "Frutas",
  [CategoryEnum.PASTA]: "Massas",
  [CategoryEnum.BREADS]: "Paes",
  [CategoryEnum.LEGUMES]: "Legumes",
  [CategoryEnum.DESSERT]: "Sobremesas",
};
export const CATEGORY_BY_ID: Record<number, string> = {
  [1]: "Graos",
  [2]: "Laticinios",
  [3]: "Carne",
  [4]: "Oleos e Gorduras",
  [5]: "Vegetais",
  [6]: "Frutas",
  [7]: "Massas",
  [8]: "Paes",
  [9]: "Legumes",
  [10]: "Sobremesas",
};

// constantes dos ingredientes
export const INGREDIENTS = [
  "CORNSTARCH",
  "WHEAT_FLOUR",
  "REFINED_SUGAR",
  "SWEET_CORN",
  "SUGAR",
  "ROYAL_BAKING_POWDER",
  "EGG",
  "BUTTER",
  "BEER",
  "SALT",
  "MILK",
  "PLUM",
  "RAISINS",
  "CINNAMON",
  "GROUND_CINNAMON",
  "UNREFINED_SUGAR",
  "WATER",
  "CORNMEAL",
  "CARROT",
  "OIL",
  "CHOCOLATE",
  "SEMI_SWEET_CHOCOLATE",
  "SPRINKLES",
  "COFFEE",
  "JELLY",
  "HONEY",
  "EGG_YOLK",
  "EGG_WHITE",
  "LIQUOR",
  "MARGARINE",
  "COCONUT_MILK",
  "COCONUT_FLOUR",
  "COCONUT",
  "SOCOCO",
  "HOMINY_CORNMEAL",
  "CHEESE",
  "GRATED_CHEESE",
  "MINAS_CHEESE",
  "BAKING_SODA",
  "FAT",
  "YOGURT",
  "CLOVES",
  "ORANGE_JUICE",
  "CONDENSED_MILK",
  "BUTTER_MILK",
  "CASSAVA",
  "HEAVY_CREAM",
  "TAPIOCA_FLOUR",
  "SWEET_TAPIOCA_FLOUR",
  "SOUR_TAPIOCA_FLOUR",
  "MILK_CREAM",
  "FENNEL",
  "SAFFRON",
  "BLACK_PEPPER",
  "SOY_SAUCE",
  "FRESH_GINGER",
  "RICE_VINEGAR",
  "NUTMEG",
  "TURMERIC",
  "PAPRIKA",
  "GARLIC",
  "ONION",
  "TOMATO",
  "BAT_LEAF",
  "PARSLEY",
  "CILANTRO",
  "OLIVE_OIL",
];
export const INGREDIENTS_LABELS: Record<string, string> = {
  [IngredientEnum.CORNSTARCH]: "Maisena",
  [IngredientEnum.WHEAT_FLOUR]: "Farinha de Trigo",
  [IngredientEnum.REFINED_SUGAR]: "Açúcar Refinado",
  [IngredientEnum.SWEET_CORN]: "Milho Verde",
  [IngredientEnum.SUGAR]: "Açúcar",
  [IngredientEnum.ROYAL_BAKING_POWDER]: "Pó Royal",
  [IngredientEnum.EGG]: "Ovo",
  [IngredientEnum.BUTTER]: "Manteiga",
  [IngredientEnum.BEER]: "Cerveja",
  [IngredientEnum.SALT]: "Sal",
  [IngredientEnum.MILK]: "Leite",
  [IngredientEnum.PLUM]: "Ameixa",
  [IngredientEnum.RAISINS]: "Uva Passa",
  [IngredientEnum.CINNAMON]: "Canela",
  [IngredientEnum.GROUND_CINNAMON]: "Canela em Pó",
  [IngredientEnum.UNREFINED_SUGAR]: "Açúcar Mascavo",
  [IngredientEnum.WATER]: "Água",
  [IngredientEnum.CORNMEAL]: "Fubá",
  [IngredientEnum.CARROT]: "Cenoura",
  [IngredientEnum.OIL]: "Óleo",
  [IngredientEnum.CHOCOLATE]: "Chocolate",
  [IngredientEnum.SEMI_SWEET_CHOCOLATE]: "Chocolate Meio Amargo",
  [IngredientEnum.SPRINKLES]: "Granulado",
  [IngredientEnum.COFFEE]: "Café",
  [IngredientEnum.JELLY]: "Geléia",
  [IngredientEnum.HONEY]: "Mel",
  [IngredientEnum.EGG_YOLK]: "Gema de Ovo",
  [IngredientEnum.EGG_WHITE]: "Clara de Ovo",
  [IngredientEnum.LIQUOR]: "Licor",
  [IngredientEnum.MARGARINE]: "Margarina",
  [IngredientEnum.COCONUT_MILK]: "Leite de Coco",
  [IngredientEnum.COCONUT_FLOUR]: "Farinha de Coco",
  [IngredientEnum.COCONUT]: "Coco",
  [IngredientEnum.SOCOCO]: "SócoCo",
  [IngredientEnum.HOMINY_CORNMEAL]: "Fubá de Canjica",
  [IngredientEnum.CHEESE]: "Queijo",
  [IngredientEnum.GRATED_CHEESE]: "Queijo Ralado",
  [IngredientEnum.MINAS_CHEESE]: "Queijo Minas",
  [IngredientEnum.BAKING_SODA]: "Bicarbonato de Sódio",
  [IngredientEnum.FAT]: "Gordura",
  [IngredientEnum.YOGURT]: "Iogurte",
  [IngredientEnum.CLOVES]: "Cravo",
  [IngredientEnum.ORANGE_JUICE]: "Suco de Laranja",
  [IngredientEnum.CONDENSED_MILK]: "Leite Condensado",
  [IngredientEnum.BUTTER_MILK]: "Mandeiga de Leite",
  [IngredientEnum.CASSAVA]: "Mandioca",
  [IngredientEnum.HEAVY_CREAM]: "Creme de Leite",
  [IngredientEnum.TAPIOCA_FLOUR]: "Polvilho",
  [IngredientEnum.SWEET_TAPIOCA_FLOUR]: "Polvilho Doce",
  [IngredientEnum.SOUR_TAPIOCA_FLOUR]: "Polvilho Azedo",
  [IngredientEnum.MILK_CREAM]: "Nata",
  [IngredientEnum.FENNEL]: "Erva doce",
  [IngredientEnum.SAFFRON]: "Açafrão",
  [IngredientEnum.BLACK_PEPPER]: "Pimenta-do-Reino",
  [IngredientEnum.SOY_SAUCE]: "Shoyo",
  [IngredientEnum.FRESH_GINGER]: "Gengibre Fresco",
  [IngredientEnum.RICE_VINEGAR]: "Vinagre de Arroz",
  [IngredientEnum.NUTMEG]: "Noz-moscada",
  [IngredientEnum.TURMERIC]: "Açafrão-da-terra",
  [IngredientEnum.PAPRIKA]: "Páprica",
  [IngredientEnum.GARLIC]: "Alho",
  [IngredientEnum.ONION]: "Cebola",
  [IngredientEnum.TOMATO]: "Tomate",
  [IngredientEnum.BAT_LEAF]: "Louro",
  [IngredientEnum.PARSLEY]: "Salsa",
  [IngredientEnum.CILANTRO]: "Coentro",
  [IngredientEnum.OLIVE_OIL]: "Azeite de Oliva",
};
export const INGREDIENTS_BY_ID: Record<number, string> = {
  [1]: "Maisena",
  [2]: "Farinha de Trigo",
  [3]: "Açúcar Refinado",
  [4]: "Milho Verde",
  [5]: "Açúcar",
  [6]: "Pó Royal",
  [7]: "Ovo",
  [8]: "Manteiga",
  [9]: "Cerveja",
  [10]: "Sal",
  [11]: "Leite",
  [12]: "Ameixa",
  [13]: "Uva Passa",
  [14]: "Canela",
  [15]: "Canela em Pó",
  [16]: "Açúcar Mascavo",
  [17]: "Água",
  [18]: "Fubá",
  [19]: "Cenoura",
  [20]: "Óleo",
  [21]: "Chocolate",
  [22]: "Chocolate Meio Amargo",
  [23]: "Granulado",
  [24]: "Café",
  [25]: "Geléia",
  [26]: "Mel",
  [27]: "Gema de Ovo",
  [28]: "Clara de Ovo",
  [29]: "Licor",
  [30]: "Margarina",
  [31]: "Leite de Coco",
  [32]: "Farinha de Coco",
  [33]: "Coco",
  [34]: "SócoCo",
  [35]: "Fubá de Canjica",
  [36]: "Queijo",
  [37]: "Queijo Ralado",
  [38]: "Queijo Minas",
  [39]: "Bicarbonato de Sódio",
  [40]: "Gordura",
  [41]: "Iogurte",
  [42]: "Cravo",
  [43]: "Suco de Laranja",
  [44]: "Leite Condensado",
  [45]: "Manteiga de Leite",
  [46]: "Mandioca",
  [47]: "Creme de Leite",
  [48]: "Polvilho",
  [49]: "Polvilho Doce",
  [50]: "Polvilho Azedo",
  [51]: "Nata",
  [52]: "Erva doce",
  [53]: "Açafrão",
  [54]: "Pimenta-do-Reino",
  [55]: "Shoyo",
  [56]: "Gengibre Fresco",
  [57]: "Vinagre de Arroz",
  [58]: "Noz-moscada",
  [59]: "Açafrão-da-terra",
  [60]: "Páprica",
  [61]: "Alho",
  [62]: "Cebola",
  [63]: "Tomate",
  [64]: "Louro",
  [65]: "Salsa",
  [66]: "Coentro",
  [67]: "Azeite de Oliva",
};
